### ISSUE TITLE
shared_ptr osx issue

### ISSUE THREAD

**Issue by rasheinstein** [POV-Ray/povray#107]
I have issues compiling for OSX mainly due to the shared_ptr problem being ambiguous. I found that since you are always using the shared_ptr in reference to boost, that it is prefixed in every location to allow easy compilation on OSX. I could create a pull request if that is required but it's just a simple search across files and replace. Thank you.

**Comment by c-lipka** [comment]
Presuming you are trying to build from the official POV-Ray 3.7.0 source code or the 3.7-stable branch, this is a duplicate to resolved issue #8. If you still experience the same problem with more recent versions, please let us know, providing us with more details (e.g. version you were trying to build, compiler error messages) and we'll re-open this issue.

**Comment by c-lipka** [comment]
(See also issue #31.)
