### ISSUE TITLE
Port of FS307 - netpbm, ppm, read bug where first data byte CR char.

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#111]
Given recent work on #110 thought I'd port this flyspray ppm bug here to github. Tested and we still have an issue reading such ppm (likely pgm too) files. 

(Copied text from FS follows from Sept 2013) 

> I've recently been working with the netpbm ppm format and I have hit what I believe to be a bug in the way ppm files are read - very likely a bug in all netpbm formats. I am aware of the long standing povray issue with the netpbm file formats header where the height and width need to be on the same line as the magic number though that is not a requirement of the official format. This bug is different.

> Namely in working with a larger number of ppm files I hit cases where a few would fail with the message : "Possible Parse Error: Unexpected EOF in PPM file" though the ppm files are fine. What is happening is that the first byte of data after the line feed (LF) (Ubuntu linux 12.04) happens to have a carriage return (CR) value.

> The code which is set up to interpret the netpbm headers is reading a lines with "file->getline (line, 1024);" and this line reading code is pulling in the first byte of data with the CR value as part of the line. When the read by binary data, 8 or 16 bits at a time, starts, the povray read code is offset into the data by one byte too many.

> The result from 10,000 meters, if input values were completely random file to file, would be netpbm read fails for size that make no sense in 1/256 files. In practice & depending on data some might never see fails while an unfortunate few might almost always fail.

> I'd make some argument any CR following a LF character should not be pulled in as part of the line read even on windows/dos systems where CRLF is the usual line termination order. I think though the real fix is better netpbm header reading code which more strictly breaks apart the header on the first whitespace character doing the last depth break, aware of the file size, so it can decide what portion of any valid sequence of whitespce characters after the decimal depth value is data and not whitespace.

> The attached tarball when unpacked has both a passing and failing case. To run "povray fails.pov" or "povray works.pov". The only difference between the two ppm files if the fails.ppm data is all 0x0D while works.ppm data bytes are all 0x0C. The image rendered is meaningless.

> [bugReadPPM.zip](https://github.com/POV-Ray/povray/files/517597/bugReadPPM.zip)

**Comment by c-lipka** [comment]
For the records: The original bug report can be found at http://bugs.povray.org/task/307.

**Comment by c-lipka** [comment]
Should be fixed with commit be34de4.
