### ISSUE TITLE
Port of FS313 - radiosity.cpp pov::RadiosityFunction::BeforeTile assertion failed

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#137]
http://bugs.povray.org/task/313

---

Details

With 3.7.0 final, rendering attached files (for Computer Engineering college course), which renders without issues in povray 3.6.1, fails with following error:

```
...
==== [Rendering...] ========================================================
povray: backend/lighting/radiosity.cpp:324: virtual void pov::RadiosityFunction::BeforeTile(int, unsigned int): Assertion `(pts >= PRETRACE_FIRST) && (pts <= PRETRACE_MAX)' failed.
```

Command line:

```
povray +K0.6500 \
+FN +Q9 +MB1 \
+W600 +H400 \
+AM1 +A0.0 +R2 \
+D +SP32 +EP4 \
+L/usr/share/povray-3.7/include \
+Imain.pov \
+Omain-0.6500.png
```

Using Arch Linux testing current:
Linux archmidi 3.12.0-1-ARCH #1 SMP PREEMPT Wed Nov 6 09:06:27 CET 2013 x86_64 GNU/Linux

Downstream bug report:
https://bugs.archlinux.org/task/37689

https://bugs.archlinux.org/task/37689
   main.pov (5.7 KiB)
   camlight.inc (3.2 KiB)

See attached zip file:

[FS331.zip](https://github.com/POV-Ray/povray/files/558702/FS331.zip)

---

Comments:

---

Comment by André Vitor de Lima Matos (andre.vmatos) - Saturday, 16 November 2013, 16:48 GMT+5

Sorry, main.pov in bug report had a little typo due to vim (B). Follow fixed version, with .pov-state dump file generated.
   main.pov (5.7 KiB)
   main-0.6500.pov-state (0.5 KiB)

---

Comment by Christoph Lipka (clipka) - Saturday, 16 November 2013, 17:46 GMT+5

Thanks for submitting this bug report.

Can you confirm that avoiding mosaic pretrace (i.e. removing the +SP32 and +EP4 options) works around this issue?

---

Comment by André Vitor de Lima Matos (andre.vmatos) - Saturday, 16 November 2013, 18:25 GMT+5

Hi. Thanks for you quick reply.
Confirming that removing given options avoid this issue.

---

Comment by Christoph Lipka (clipka) - Saturday, 16 November 2013, 19:17 GMT+5

Preliminary fix submitted as change #6092.

(The git commit for this is: 278eb39 was Christoph Lipka, Date: Mon Dec 16 08:53:42 2013 +0100)

---

Comment by Grimbert Jérôme (Le_Forgeron) - Monday, 31 March 2014, 21:14 GMT+5

Grepping the code for BeforeTile, it seems that all but one calls are using only one parameter, defaulting to pts=FINAL_TRACE) (and FINAL_TRACE is 255 a.k.a UCHAR_MAX / OT_PASS_FINAL ).

Instrumenting the code of tracetask, the radiosity is done via TraceTask::SimpleSamplingM0P which does not provide the second parameter. Hence the failure of assertion.

---

Comment by Grimbert Jérôme (Le_Forgeron) - Sunday, 11 May 2014, 16:10 GMT+5

I would suggest the following correction, because the mosaic preview at that time is the final render (as far as radiosity is concerned, the radiosity computation has been done previously).

The false/ true change is for the "isFinalTrace" member of RadiosityFunction / radiosity.

Did I misinterpret anything ?

```
--- a/smp/source/backend/scene/view.cpp       Sat Mar 08 17:08:19 2014 +0100
+++ b/smp/source/backend/scene/view.cpp       Sun May 11 13:03:01 2014 +0200
@@ -1094,7 +1094,7 @@
        {
                // do render with mosaic preview start size
                for(int i = 0; i < maxRenderThreads; i++)
-                       viewThreadData.push_back(dynamic_cast<ViewThreadData *>(renderTasks.AppendTask(new TraceTask(&viewData, 0, jitterscale, aathreshold, aadepth, aaGammaCurve, previewstartsize, false, false, highReproducibility))));
+                       viewThreadData.push_back(dynamic_cast<ViewThreadData *>(renderTasks.AppendTask(new TraceTask(&viewData, 0, jitterscale, aathreshold, aadepth, aaGammaCurve, previewstartsize, false, true/*false*/, highReproducibility))));

                for(unsigned int step = (previewstartsize >> 1); step >= previewendsize; step >>= 1)
                {
@@ -1109,7 +1109,7 @@

                        // do render with current mosaic preview size
                        for(int i = 0; i < maxRenderThreads; i++)
-                               viewThreadData.push_back(dynamic_cast<ViewThreadData *>(renderTasks.AppendTask(new TraceTask(&viewData, 0, jitterscale, aathreshold, aadepth, aaGammaCurve, step, true, ((step == 1) && (tracingmethod == 0)), highReproducibility))));
+                               viewThreadData.push_back(dynamic_cast<ViewThreadData *>(renderTasks.AppendTask(new TraceTask(&viewData, 0, jitterscale, aathreshold, aadepth, aaGammaCurve, step, true, true/*((step == 1) && (tracingmethod == 0))*/, highReproducibility))));
                }

                // do render everything again if the final mosaic preview block size was not one or anti-aliasing is required
```

**Comment by wfpokorny** [comment]
In my testing the test case still fails in POV-Ray 3.7.0 but runs OK with Christoph's fix in the current 3.7.1. 

I ported this to github instead of closing it out because Jérôme's code changes have not been adopted in 3.7.1 and the question in his last comment not answered.

**Comment by c-lipka** [comment]
> I would suggest the following correction, because the mosaic preview at that time is the final render (as far as radiosity is concerned, the radiosity computation has been done previously).
>
> The false/ true change is for the "isFinalTrace" member of RadiosityFunction / radiosity.
>
> Did I misinterpret anything ?

Setting the parameter to `true` in anything but the genuinely final pass would wreak havoc on the abort-continue mechanism.

We may need to use two separate parameters: One to specifiy whether this is the main render as opposed to a radiosity pretrace, and one to specify whether this is the final pass as opposed to a mosaic preview.

Alternatively, we might make the parameter an enum: Radiosity pretrace, mosaic preview pass, and final pass.

**Comment by wfpokorny** [comment]
With the above commit now merged into the master branch do you consider this issue closed?
