### ISSUE TITLE
Port of FS273 - No automatic backup files from inc files

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#170]
http://bugs.povray.org/task/273

(Windows)

---------------
Details:

If enabled, POVray always created backups of pov and inc files once per session. 
Now using 3.7 RC6 only pov file backups are created but not from inc files.

**Comment by c-lipka** [comment]
Did you test this? Because I can't confirm this here, neither with official 3.7.0 release nor with 3.7.1-alpha.

**Comment by wfpokorny** [comment]
No. This was a windows issue and I don't run windows. If you see whatever backup happening the user did not I say we close this out. I can go back to flyspray and close it with a comment asking them to open a new github issue - if they are still seeing problems. Let me know.     
   
With the windows bugs on flyspray, I've been digging into code when the mood hits me and I think I 'might' be able to quickly find something as with #168.  No promises I'll again dig in such cases. There, I end up burning hours trying to understand code I don't know to come up with a guess or two I cannot test. ;-)

FYI. There are a bunch of interface related windows issues yet to be ported to github. Those will mostly be coming here untested for others to pick up. I'll try to remember to add a longer comment at the top like (Windows, I cannot test on port to github).
