### ISSUE TITLE
Coredump due recent 3.7.1 parser updates. 

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#175]
At commit 5f89d41 (December 15, 2016) in master branch, getting core dump (Ubuntu 16.04) for the following code: 

```
#version 3.7;
global_settings { assumed_gamma 1 }
#declare FnWreathLeaves = function {
    pattern { density_file df3 Wreath.df3 interpolate 2 }   // Missing quotes
 // pattern { density_file df3 "Wreath.df3" interpolate 2 } // OK
}
```
as in: 

> ==== [Parsing...] ==========================================================
> terminate called after throwing an instance of 'pov_base::Exception'
>   what():  Attempt to free NULL pointer.
> Aborted (core dumped)
> 

where we used to get: 

> ==== [Parsing...] ==========================================================
> File 'example.pov' line 4: Parse Error: Expected 'string expression', undeclared
>  identifier 'Wreath' found instead
> Fatal error in parser: Cannot parse input.
> Render failed
> 

Adding on Dec 16, 2016 - I've since seen a similar coredump on another SDL syntax error. Perhaps something general with SDL syntax issues.

**Comment by c-lipka** [comment]
Was the other also related to a density file?

**Comment by wfpokorny** [comment]
Something else, but my old brain isn't pulling it to the surface at the moment.

**Comment by wfpokorny** [comment]
I'll also mention here for the record with the recent updates to generically look for unpaired braces and such, other errors are now caught by this code where it might have previously been code and a message specific to say the light_source { block. 

Others might pick up the changes in parser error messages.

**Comment by c-lipka** [comment]
Let us know if you ecnounter any further core dumps.
