### ISSUE TITLE
Port of FS129 - Hash arrays

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#198]
http://bugs.povray.org/task/129

(A 'dictonary' feature was added to 3.7.1 I believe largely addresses this issue. See: http://wiki.povray.org/content/Reference:Array for more detail. However, it was not clear to me from the newsgroup discussions whether all parties consider this issue closed so I've ported the issue.)

---------------
Details:

Currently, array items may only be referenced by their index number (an integer). It would be nice to also be able to assign string values as array indexes, as in other scripting languages.

---------------
Comments:

---
Comment by Grimbert Jérôme (Le_Forgeron) - Thursday, 10 June 2010, 17:35 GMT+5

How do you loop over such arrays ?
POV-SDL is not php, I do not feel the need of a foreach()... nor a ksort().

Nice seems a bit frivolous here.

---
Comment by Mike H (SharkD) - Sunday, 20 June 2010, 05:34 GMT+5

It's easier to remember names than index numbers. If you have a group of related items (stored objects, variables, macros, etc.) then you can use the same naming scheme throughout. And, if you have more than one array you don't have to worry about the arrays being equal in length, or if they have had items added or removed to/from them: the index will always remain the same.

---
Comment by Thorsten Fröhlich (thorsten) - Sunday, 20 June 2010, 13:05 GMT+5

POV-Ray is not a scripting language in the sense of the ones that offer the feature you are talking about. You can declare special indices in advance, then they are easier to remember.

---
Comment by Mike H (SharkD) - Sunday, 20 June 2010, 13:43 GMT+5

Er, what? That sounds bogus to me. "POV-Ray is not a thing that has that feature, therefore it is not a thing that has that feature." That is the point of "Feature Requests" isn't it, or am I retarded? Don't the POV-Ray docs themselves brag about how you're able to write a complete ray-tracer within POV-Ray using only SDL? And plenty of non-"scripting" languages support hash (associative) arrays. Or do C++ and C# not count?

---
Comment by Grimbert Jérôme (Le_Forgeron) - Friday, 29 October 2010, 16:52 GMT+5

what about simply declaring your "string" index with classical #declare.

Instead of

`arr["Mike"] = foo;`

You can already have

```
#declare Mike = 3;
...

arr[Mike] = foo;
```

Associative array in C++ are called maps, not arrays.
(unless you want only an #enum for povray ?
#enum { Mike, Thorsten, Jerome } ???
)

---
Comment by Mike H (SharkD) - Sunday, 19 December 2010, 22:55 GMT+5

What if:

```
#declare Mike = 3;
#declare Thorsten = 7;
#declare Jerome = 32;

#declare MyArray = array[3]
#declare MyArray[Mike] = pigment{White}
#declare MyArray[Thorsten] = pigment{Blue}
#declare MyArray[Jerome] = pigment{Black}
```

Isn't going to work.

---
Comment by Grimbert Jérôme (Le_Forgeron) - Tuesday, 21 December 2010, 16:56 GMT+5

I can lead the horse to water, but I cannot make it drink.

Good practices would be for the last code to have instead:

```
#declare Mike = 3;
#declare Thorsten = 7;
#declare Jerome = 32;
#declare Last_Entry = 33;// or even " = 1+max(Jerome,Thorsten,Mike); "


#declare MyArray = array[Last_Entry]
#declare MyArray[Mike] = pigment{White}
#declare MyArray[Thorsten] = pigment{Blue}
#declare MyArray[Jerome] = pigment{Black}
```

(and we might be missing a few semi-colons)

**Comment by c-lipka** [comment]
`dictionary` does indeed seem to provide the requested feature. Mixed indexing (allowing both integers and strings as indices into the same container) would be excessively difficult to implement in the current parser.
