### ISSUE TITLE
undefined reference to `boost::this_thread::yield()

### ISSUE THREAD

**Issue by ce3a** [POV-Ray/povray#22]
Building POV-Ray on Ubuntu 13.10 64Bit returns the following error:
```
../source/libpovray.a(tokenize.o): In function `pov::Parser::Get_Token()':
tokenize.cpp:(.text+0x24b1): undefined reference to `boost::this_thread::yield()'
collect2: error: ld returned 1 exit status
```
`libboost-dev` version is `1.53.0.0ubuntu2`

**Comment by LeForgeron** [comment]
it's a symptom that boost need some more hints about what library to use.

adding LIBS="-lboost_system -lboost_thread" in configure command usually fix that problem.

**Comment by c-lipka** [comment]
Any update on this one? Otherwise I'd be inclined to close this issue.

**Comment by LeForgeron** [comment]
It's due to a change in boost... should we adapt to newer versions ? (to handle that problem automatically).
Testing a solution that work with all boost versions might be tedious (well, at least an old and new versions would be needed)
Or do we just document that workaround ?

**Comment by c-lipka** [comment]
I'm not sure whether it is a problem anymore with the current master branch. Hence my poll in news://news.povray.org/povray.unix -- let's see what that turns up.

**Comment by c-lipka** [comment]
Applying the old "no news is good news" rule, I'm closing this issue.
