### ISSUE TITLE
Text in Windows "Open with" file menu

### ISSUE THREAD

**Issue by posfan12** [POV-Ray/povray#257]
When installing multiple versions of POV-Ray on Windows, each version adds a new entry to the "Open with" dialog. Unfortunately, the text shown in that dialog is the same, so there's no way to tell the apart the different POV-Ray 3.7 versions, so you have to guess which is correct. I think the text supplied here should be different for every version.

**Comment by c-lipka** [comment]
The newest beta (3.7.1-beta.5) should now identify as "POV-Ray for Windows 3.7-beta" when added to the "Open with" file menu; however, the Windows Explorer seems reulctant to update this information when the newest beta replaces an older one, so you may continue to see "POV-Ray for Windows 3.7" instead. There isn't much we can do about this.

**Comment by posfan12** [comment]
I also pinned the beta to my Start Menu, but it says "POV-Ray" and nothing else.

**Comment by posfan12** [comment]
I also pinned the beta to my Start Menu, but it says "POV-Ray" and nothing else. Did you fix this too?

**Comment by c-lipka** [comment]
No, I didn't change that.

To my knowledge, the title for pinned programs is taken from the link through which you start the program, so we can't change one without the other.

Note that you can change the title of a pinned program manually by right-clicking the icon, then right-clicking the name in the menu that pops up, then selecting "properties", and in that dialog go to the "general" tab; the name of the link (as pinned, not as in the start menu) will be shown and editable right at the top of the dialog.

If you deem that workaround an insufficient solution, please do open a new issue.

**Comment by posfan12** [comment]
You're right. The shortcut in the regular start menu folder also just says "POV-Ray".

**Comment by posfan12** [comment]
I tried to manually remove POV-Ray 3.7.0 from the "open with" menu using the registry. I deleted POV-Ray from "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.pov\OpenWithList". But it still appears in the list. I did restart the machine first.

I am also unable to manually add the beta to the "Open with" list. Even when I browse to the correct .exe, it still reverts to 3.7.0 instead.



![reg_open_with](https://cloud.githubusercontent.com/assets/13713396/24532944/42c80082-1592-11e7-94fd-2a361191c72d.png)
![pov_open_with](https://cloud.githubusercontent.com/assets/13713396/24532993/a2b370d0-1592-11e7-9d61-4754a44f612f.png)

**Comment by c-lipka** [comment]
> I tried to manually remove POV-Ray 3.7.0 from the "open with" menu using the registry. I deleted POV-Ray from "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts.pov\OpenWithList". But it still appears in the popup list.

I'm no expert on Windows' file associations stuff. My suspicion is that "POV-Ray for Windows v3.7" is in there via the `OpenWithProgids` key, and/or the data in `HKEY_CLASSES_ROOT`. (Note how your registry also doesn't contain entries for Notepad and WordPad, and still they're there, most certainly because `.pov` is registered as a text-ish file type.)

As for why you can't get a separate entry for the POV-Ray for Windows beta, that's certainly not POV-Ray's fault: In the `OpenWithList` key, the Explorer only stores the names of the binaries, not their location.

**Comment by posfan12** [comment]
OpenWithProgids only has two items: (Default) and POV-Ray.scene.

HKEY_CLASSES_ROOT has an entry for the .pov extension, but I can't delete it. I get an error.

I did edit "HKEY_CLASSES_ROOT\POV-Ray.Scene\shell\Open" to point to the beta. I think that fixed the issue.

**Comment by c-lipka** [comment]
It is my understanding that this issue has been solved. If not, let us know.
