### ISSUE TITLE
backend/math/polysolv.cpp:1590]: (style) Array index 'i' is used before limits check.

### ISSUE THREAD

**Issue by dcb314** [POV-Ray/povray#275]
Source code is

    while ((fabs(c0[i]) < SMALL_ENOUGH) && (i < n))
    {
        i++;
    }

Suggest sanity check array index before use, not after.

**Comment by c-lipka** [comment]
The current source code does not have a file named `backend/math/polysolv.cpp`.
What version are you referring to?

**Comment by c-lipka** [comment]
Presuming you're referring to what is now `core/math/polynomialsolver.cpp` line 1593, there's no fault in that: `c0[n]` _is_ a valid array element (see documentation of the function in line 1549).

**Comment by c-lipka** [comment]
Changed for the sake of performance in commit 4be26ab.
