### ISSUE TITLE
Port of FS243 - Sphere sweep behaves wrong when scaled

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#285]
http://bugs.povray.org/task/243  (Simon (infoised))

(When scaled with identical negative values for x,y,z as in scale -1)

(also sphere_sweep related: #59, #147 #287)

---------------
Details:

The sphere_sweep renders well when specified directly, but when it is scaled, its bounding box is calculated incorrectly, which clips the object so it almost disappears.

The effect is present for all three types of splines.

I'm attaching a test scene and the rendering result. The saving of the object with #declare has no effect, I just wanted to show both transformed and untransformed version.

I don't think this issue is related to other artifacts occurring with sphere_sweep, as it is obviously an issue of the internal bounding box.
   fig_bug_sweep.png (7 KiB)
   fig_bug_sweep.pov (0.7 KiB)

See zip file:
[FS243.zip](https://github.com/POV-Ray/povray/files/966768/FS243.zip)

---------------
Comments:

---
Comment by Thorsten Fröhlich (thorsten) - Monday, 28 May 2012, 00:03 GMT+5

The bounding of spline-based sphere sweeps never worked right and it known to have many bugs, in particular because the bounding box does not correctly consider splines were the curve extends beyond the control points. Transformations just make the problems more apparent. The best solution is to manually bound sphere-sweeps.

---
Comment by Simon (infoised) - Monday, 25 February 2013, 21:27 GMT+5

Found the error. It's an easy fix. The SphereSweep::Scale has a special case for scaling if scaling is uniform: it simply multiplies all vectors AND ALL RADII by the scaling factor. This makes radius negative for negative scaling factors, which makes the bounding box shrink instead of grow. The code should be

```
void SphereSweep::Scale(const VECTOR Vector, const TRANSFORM *tr)
{
if((Vector[X] != Vector[Y]) || (Vector[X] != Vector[Z]))
{
        if(Trans == NULL)
                Trans = Create_Transform();
}

if(Trans == NULL)
{
        for(int i = 0; i < Num_Modeling_Spheres; i++)
        {
                VScaleEq(Modeling_Sphere[i].Center, Vector[X]);
                Modeling_Sphere[i].Radius *= fabs(Vector[X]); /*missing absolute value*/
        }
        Compute();
        Compute_BBox();
}
else
Transform(tr);
}
```

This fixes the bounding box for linear_spline (linear splines never stick out of their bounding box, so they don't have the same problems as the other types).

As for other problems with bounding boxes: for cubic_spline and b_spline, the bounding box in the code is heuristically made a bit bigger, but may still be too small in some cases. It is possible to find roots of the derivatives of cubic polynomials that describe the spline to get exact bounding values.

---
Comment by Grimbert Jérôme (Le_Forgeron) - Friday, 07 March 2014, 03:26 GMT+5

I agree, the scaling of the radius should use the absolute value. scale -1 is traditional, it shouldn't break the sphere_sweep when used alone or first.

**Comment by c-lipka** [comment]
The fix proposed by Simon does not work for cases where the user deliberately specifies negative values for some radii.

**Comment by wfpokorny** [comment]
Closing. The fix for this has been merged into the master branch.
