### ISSUE TITLE
debian 7  __collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by godeye** [POV-Ray/povray#316]
`avx_a-avxportablenoise.o `test -f 'x86/avx/avxportablenoise.cpp' || echo './'`x86/avx/avxportablenoise.cpp
mv -f x86/avx/.deps/libx86avx_a-avxportablenoise.Tpo x86/avx/.deps/libx86avx_a-avxportablenoise.Po
rm -f libx86avx.a
ar cru libx86avx.a x86/avx/libx86avx_a-avxnoise.o x86/avx/libx86avx_a-avxportablenoise.o
ranlib libx86avx.a
g++ -DHAVE_CONFIG_H -DPOVLIBDIR=\"/usr/local/share/povray-3.7\" -DPOVCONFDIR=\"/usr/local/etc/povray/3.7\" -DPOVCONFDIR_BACKWARD=\"/usr/local/etc\" -I. -I..  -I../unix/povconfig -I../platform/unix -I../platform/x86 -I../vfe -I../vfe/unix -I../unix -I../source -I/usr/include/OpenEXR   -pthread -I/usr/include  -I/usr/include -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread -mavx -mfma4 -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread -MT x86/avxfma4/libx86avxfma4_a-avxfma4noise.o -MD -MP -MF x86/avxfma4/.deps/libx86avxfma4_a-avxfma4noise.Tpo -c -o x86/avxfma4/libx86avxfma4_a-avxfma4noise.o `test -f 'x86/avxfma4/avxfma4noise.cpp' || echo './'`x86/avxfma4/avxfma4noise.cpp
mv -f x86/avxfma4/.deps/libx86avxfma4_a-avxfma4noise.Tpo x86/avxfma4/.deps/libx86avxfma4_a-avxfma4noise.Po
rm -f libx86avxfma4.a
ar cru libx86avxfma4.a x86/avxfma4/libx86avxfma4_a-avxfma4noise.o
ranlib libx86avxfma4.a
g++ -DHAVE_CONFIG_H -DPOVLIBDIR=\"/usr/local/share/povray-3.7\" -DPOVCONFDIR=\"/usr/local/etc/povray/3.7\" -DPOVCONFDIR_BACKWARD=\"/usr/local/etc\" -I. -I..  -I../unix/povconfig -I../platform/unix -I../platform/x86 -I../vfe -I../vfe/unix -I../unix -I../source -I/usr/include/OpenEXR   -pthread -I/usr/include  -I/usr/include -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread -mavx2 -mfma -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread -MT x86/avx2fma3/libx86avx2fma3_a-avx2fma3noise.o -MD -MP -MF x86/avx2fma3/.deps/libx86avx2fma3_a-avx2fma3noise.Tpo -c -o x86/avx2fma3/libx86avx2fma3_a-avx2fma3noise.o `test -f 'x86/avx2fma3/avx2fma3noise.cpp' || echo './'`x86/avx2fma3/avx2fma3noise.cpp
mv -f x86/avx2fma3/.deps/libx86avx2fma3_a-avx2fma3noise.Tpo x86/avx2fma3/.deps/libx86avx2fma3_a-avx2fma3noise.Po
rm -f libx86avx2fma3.a
ar cru libx86avx2fma3.a x86/avx2fma3/libx86avx2fma3_a-avx2fma3noise.o
ranlib libx86avx2fma3.a
make[2]: Leaving directory '/root/povray/platform'
Making all in unix
make[2]: Entering directory '/root/povray/unix'
depbase=`echo disp_sdl.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I..  -I../unix/povconfig -I.. -I../source -I../source -I../platform/unix -I../platform/x86 -I../vfe -I../vfe/unix -I/usr/include/OpenEXR   -pthread -I/usr/include  -I/usr/include  -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread -MT disp_sdl.o -MD -MP -MF $depbase.Tpo -c -o disp_sdl.o disp_sdl.cpp &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo disp_text.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I..  -I../unix/povconfig -I.. -I../source -I../source -I../platform/unix -I../platform/x86 -I../vfe -I../vfe/unix -I/usr/include/OpenEXR   -pthread -I/usr/include  -I/usr/include  -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread -MT disp_text.o -MD -MP -MF $depbase.Tpo -c -o disp_text.o disp_text.cpp &&\
mv -f $depbase.Tpo $depbase.Po
g++  -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread  -L/usr/lib/x86_64-linux-gnu  -L/usr/lib -o povray disp_sdl.o disp_text.o ../vfe/libvfe.a ../source/libpovray.a ../vfe/libvfe.a ../platform/libplatform.a ../platform/libx86.a ../platform/libx86avx.a ../platform/libx86avxfma4.a ../platform/libx86avx2fma3.a -lSM -lICE -lX11  -lIlmImf -lIlmImf -lImath -lHalf -lIex -lIexMath -lIlmThread -lpthread  -lIlmThread -ltiff -ljpeg -lpng -lz -lrt -lm -lboost_thread  -pthread  -lboost_system
../source/libpovray.a(openexr.o): In function `Imf_2_2::TypedAttribute<std::string>::typeName() const':
openexr.cpp:(.text._ZNK7Imf_2_214TypedAttributeISsE8typeNameEv[_ZNK7Imf_2_214TypedAttributeISsE8typeNameEv]+0x1): undefined reference to `Imf_2_2::TypedAttribute<std::string>::staticTypeName()'
../source/libpovray.a(openexr.o):(.rodata._ZTVN7Imf_2_214TypedAttributeISsEE[_ZTVN7Imf_2_214TypedAttributeISsEE]+0x30): undefined reference to `Imf_2_2::TypedAttribute<std::string>::writeValueTo(Imf_2_2::OStream&, int) const'
../source/libpovray.a(openexr.o):(.rodata._ZTVN7Imf_2_214TypedAttributeISsEE[_ZTVN7Imf_2_214TypedAttributeISsEE]+0x38): undefined reference to `Imf_2_2::TypedAttribute<std::string>::readValueFrom(Imf_2_2::IStream&, int, int)'
collect2: error: ld returned 1 exit status
Makefile:460: recipe for target 'povray' failed
make[2]: *** [povray] Error 1
make[2]: Leaving directory '/root/povray/unix'
Makefile:654: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/povray'
Makefile:446: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by wfpokorny** [comment]
If you enter the command: 

'ldconfig -p | grep IlmImf' 

do you see something similar to: 

```
	libIlmImfUtil-2_2.so.22 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libIlmImfUtil-2_2.so.22
	libIlmImf-2_2.so.22 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22
```

as the result? If not, perhaps that openexr dependency is not installed - or installed in a standard location - on the machine where you are building.

**Comment by godeye** [comment]
libIlmImfUtil-2_2.so.22 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libIlmImfUtil-2_2.so.22
	libIlmImf.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libIlmImf.so.6
	libIlmImf-2_2.so.22 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22

**Comment by godeye** [comment]
`/s/povray# ./configure COMPILED_BY="your name <email@address>"

===============================================================================
Configure POV-Ray version 3.7.1-rc.1
===============================================================================

This is an unofficial version compiled by:
 your name <email@address>
The POV-Ray Team(tm) is not responsible for supporting this version.

Environment
-----------
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether $C_INCLUDE_PATH contains the "." path... no
checking whether $CPLUS_INCLUDE_PATH contains the "." path... no

Programs
--------
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether the g++ compiler works... yes
checking how to run the C++ preprocessor... g++ -E
checking for C++ compiler vendor... gnu
checking for g++ version... 4.9.2
checking for ranlib... ranlib
checking for stat format option... --format=

Libraries
---------
checking whether to link with cygwin DLL... no
checking whether to enable static linking... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for boostlib >= 1.38... yes
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
checking whether the boost thread library is usable... yes
checking for sin in -lmkl... no
checking for sin in -lm... yes
checking for clock_gettime in -lrt... yes
checking whether to use the ZLIB library... yes
checking for library containing zlibVersion... -lz
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for libz version >= 1.2.1... 1.2.8, ok
checking whether to use the PNG library... yes
checking for library containing png_get_libpng_ver... -lpng
checking png.h usability... yes
checking png.h presence... yes
checking for png.h... yes
checking for libpng version >= 1.2.5... 1.2.50, ok
checking whether to use the JPEG library... yes
checking for library containing jpeg_std_error... -ljpeg
checking jpeglib.h usability... yes
checking jpeglib.h presence... yes
checking for jpeglib.h... yes
checking for libjpeg version >= 6b (62)... 62, ok
checking whether to use the TIFF library... yes
checking for library containing TIFFGetVersion... -ltiff
checking tiffio.h usability... yes
checking tiffio.h presence... yes
checking for tiffio.h... yes
checking for libtiff version >= 3.6.1... 4.0.8, ok
checking whether to use the OpenEXR library... yes
checking for pkg-config... pkg-config
checking for OpenEXR's pkg-config... yes
checking for OpenEXR version >= 1.2... 2.2.0, ok
checking OpenEXR/ImfCRgbaFile.h usability... yes
checking OpenEXR/ImfCRgbaFile.h presence... yes
checking for OpenEXR/ImfCRgbaFile.h... yes
checking for ImfInputReadPixels in -lIlmImf... yes
checking for X... libraries /usr/lib, headers /usr/include
checking whether -R must be followed by a space... neither works
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking X11/Xlib.h usability... yes
checking X11/Xlib.h presence... yes
checking for X11/Xlib.h... yes
checking for XFlush in -lX11... yes
checking X11/xpm.h usability... no
checking X11/xpm.h presence... no
checking for X11/xpm.h... no
checking whether to enable the watch cursor... no
checking for sdl-config... no
checking for libSDL... not found
configure: WARNING: the preview display is disabled

Language constructs and functions
---------------------------------
checking whether time.h and sys/time.h may both be included... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking for unistd.h... (cached) yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking size of int... 4
checking size of long int... 8
checking size of size_t... 8
checking size of float... 4
checking for working memcmp... yes
checking for vsnprintf... yes
checking for getcwd... yes
checking for readlink... yes
checking for nanosleep... yes
checking for usleep... yes
checking for useconds_t... yes
checking for clock_gettime... yes
checking whether CLOCK_MONOTONIC is declared... yes
checking whether CLOCK_REALTIME is declared... yes
checking whether CLOCK_PROCESS_CPUTIME_ID is declared... yes
checking whether CLOCK_THREAD_CPUTIME_ID is declared... yes
checking for clockid_t... yes
checking for getrusage... yes
checking whether RUSAGE_SELF is declared... yes
checking whether RUSAGE_THREAD is declared... yes
checking whether RUSAGE_LWP is declared... yes
checking for gettimeofday... yes
checking for asinh... yes

Compiling
---------
checking whether to enable pipes for communications... yes
checking whether g++ accepts -pipe... yes
checking whether g++ accepts -Wno-multichar... yes
checking whether g++ accepts -Wno-write-strings... yes
checking whether g++ accepts -fno-enforce-eh-specs... yes
checking whether g++ accepts -Wno-non-template-friend... yes
checking whether to enable I/O restrictions... yes
checking whether to enable debugging... no
checking whether to enable profiling... no
checking whether to enable stripping... yes
checking whether g++ accepts -s... yes
checking whether to enable optimizations... yes
checking whether g++ accepts -O3... yes
checking whether g++ accepts -ffast-math... yes
checking whether to enable architecture-specific optimizations... yes
checking whether g++ accepts -xHost... no
checking whether g++ accepts -march=native... yes
checking which architecture to optimize for... x86_64-unknown-linux-gnu (using -march=native)
checking whether C++ compiler accepts -mavx... yes
checking whether C++ compiler accepts -mavx2... yes
checking whether C++ compiler accepts -mfma... yes
checking whether C++ compiler accepts -mfma4... yes

Floating Point Features
-----------------------
checking limits usability... yes
checking limits presence... yes
checking for limits... yes
checking whether NaNs are supported... yes
checking cmath usability... yes
checking cmath presence... yes
checking for cmath... yes
checking whether NaNs can be identified using std::isnan()... no
checking whether NaNs can be identified using global isnan()... no
checking whether NaNs can be identified by comparison to themselves... no
checking whether infinite values are supported... yes
checking for cmath... (cached) yes
checking whether infinities can be identified using std::isinf()... no
checking whether infinities can be identified using global isinf()... no
checking whether infinities can be identified by comparison to the maximum value... yes

Makefiles
---------
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating source/Makefile
config.status: creating vfe/Makefile
config.status: creating platform/Makefile
config.status: creating unix/Makefile
config.status: creating config.h
config.status: executing depfiles commands

===============================================================================
POV-Ray 3.7.1-rc.1 has been configured.

Built-in features:
  I/O restrictions:          enabled
  X Window display:          disabled
  Supported image formats:   gif tga iff ppm pgm hdr png jpeg tiff openexr
  Unsupported image formats: -

Compilation settings:
  Build architecture:  x86_64-unknown-linux-gnu
  Built/Optimized for: x86_64-unknown-linux-gnu (using -march=native)
  Compiler vendor:     gnu
  Compiler version:    g++ 4.9.2
  Compiler flags:      -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread

Type 'make check' to build the program and run a test render.
Type 'make install' to install POV-Ray on your system.

The POV-Ray components will be installed in the following directories:
  Program (executable):       /usr/local/bin
  System configuration files: /usr/local/etc/povray/3.7
  User configuration files:   /root/.povray/3.7
  Standard include files:     /usr/local/share/povray-3.7/include
  Standard INI files:         /usr/local/share/povray-3.7/ini
  Standard demo scene files:  /usr/local/share/povray-3.7/scenes
  Documentation (text, HTML): /usr/local/share/doc/povray-3.7
  Unix man page:              /usr/local/share/man
===============================================================================

**Comment by godeye** [comment]
problem solved 
i have apt-get install gcc and apt-get install build-essential
