### ISSUE TITLE
Boost 1.65.0 incompatibility

### ISSUE THREAD

**Issue by ilovezfs** [POV-Ray/povray#317]
As of Boost 1.65.0, the tr1 headers have all been removed. However, povray master is still unconditionally including them, as here: https://github.com/POV-Ray/povray/blob/master/unix/povconfig/syspovconfig.h#L59

This renders povray incompatible with Boost >= 1.65.0. It would be great if you could add compatibility for the current version of Boost. Thanks!

**Comment by fxcoudert** [comment]
Patch fixing the issue: [tr1.diff.txt](https://github.com/POV-Ray/povray/files/1271988/tr1.diff.txt)

**Comment by c-lipka** [comment]
Please test the `hotfix/issue_317` branch, which should fix the issue and is scheduled to be merged back into the `release/v3.8.0` branch (which in turn will be merged back into the `master` branch).

**Comment by ilovezfs** [comment]
@c-lipka looks like 3.7.0.4 is good. There's a minor header issue. I think it should `#include <cstdlib>` in `source/frontend/processrenderoptions.cpp`. The errors are

```
/usr/bin/clang++ -std=c++11 -stdlib=libc++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../source/backend -I../source/base -I../source/frontend -I../unix -I../vfe -I../vfe/unix -F/usr/local/Frameworks -pthread -I/usr/local/opt/boost/include  -pipe -Wno-multichar -Wno-write-strings -O3 -ffast-math -march=native -Os -w -pipe -march=native -mmacosx-version-min=10.11 -D_THREAD_SAFE -c -o frontend/processrenderoptions.o frontend/processrenderoptions.cpp
frontend/processrenderoptions.cpp:463:59: error: use of undeclared identifier 'atof'
                                                err = POVMSUtil_SetFloat(&decobj, kPOVAttrib_Value, atof(ptr));
                                                                                                    ^
frontend/processrenderoptions.cpp:516:15: error: use of undeclared identifier 'atof'
                        floatval = atof(param);
                                   ^
2 errors generated.
make[2]: *** [frontend/processrenderoptions.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by ilovezfs** [comment]
@c-lipka full build log is here: https://gist.github.com/ilovezfs/d4f1368f5473fd1ae26a53d41e1b751a

**Comment by c-lipka** [comment]
I'll look into the `atof` issue, but it's certainly not Boost 1.65 related ;)

Did you also find the time to test the current 3.8.0?

**Comment by ilovezfs** [comment]
>but it's certainly not Boost 1.65 related 

It's indirectly related because the Boost fixes require the switch to C++11, which is what triggered it, I believe.

>Did you also find the time to test the current 3.8.0?

Not yet, but I will try it.

**Comment by c-lipka** [comment]
The current `hotfix/issue_317_v370` branch should fix the `atof` issue in the v3.7.0.x code. Please have a look, and let me know if you get any additional errors.

**Comment by c-lipka** [comment]
Any feedback on the `hotfix/issue_317_v370` branch?

**Comment by ilovezfs** [comment]
Both hotfix/issue_317_v370 and v3.8.0-alpha.9387404 build fine :)
