### ISSUE TITLE
message pane not copyable

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#325]
### Summary

text is not selectable in message window, and there is no context menu to copy the entire window's output for bug reports as requested by these defect reports.

### Environment

  - Source code Git tag: v3.7.0.0
  - POV-Ray version: v3.7.0+msvc10.win64 -->
  - Operating system: Windows 7
  - Hardware platform: x86-64

### Steps to Reproduce

 1. run pov+ini
 2. right click on message window
 3. try to select text from message window

### Expected Behavior

should be able to do something to copy output from message window. but this is not currently possible.

### Actual Behavior

nothing happens

### Suggested Solution

put in code for context menu and make message window not a graphic but a rich text edit control and make it "readonly" in style.

**Comment by c-lipka** [comment]
Took the liberty to strip irrelevant portions from your issue report.

**Comment by wfpokorny** [comment]
I'm not a windows user, but in a similar issue #245, Christoph wrote: 

`...very same information in the message pane, which you can copy to the clipboard using the "Edit / Copy Pane" menu option.`

which to me at least sounds like what you want to do. Suppose the issues are similar in any case.

**Comment by c-lipka** [comment]
The message pane can indeed be copied via the `Copy Pane` entry in the `Edit` menu.

Making the message pane selectable and provide a context menu might be neat, but is pretty low on our ToDo-list. The POV-Ray for Windows GUI urgently needs a complete re-write anyway.
