### ISSUE TITLE
rendering limited to video card RAM. RAM is too small for wall-size images

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#326]
### Summary

[old] FEATURE REQUEST:
1. rendering is currently limited to video card RAM. I need rendering to disk. I have 64GB RAM but a 2GB video card. I would like to have the old-style Buffer_Output and Buffer_size brought back, or a more reasonable version of that that I don't have to calculate the size of 9at least provide us the math in manuals).  some better parameters than buffer size would be buffer_width, buffer_height, buffer_bits_per_color and should be used for a temporary buiffer. 
math in the help should be provided to show how large the provisioned disk space would be. if settings>currently available space, an error should be thrown.
size=(width*height*bitsPerColor*3/8)
or
width=aspectratio*sqrt(buffersize/bitspercolor/3)
height=(1/aspectRatio)*sqrt(buffersize/bitspercolor/3)
2. it should not consistently fail on image write to disk without ini like 3.7 currently has.

### Environment

  - Source code Git tag: v3.7.0.0
  - POV-Ray version: v3.7.0+msvc10.win64
  - Operating system: Windows 7
  - Hardware platform: x86-64

### Steps to Reproduce

 1. 
 2. 
 3. 

### Render Settings

~~~
~~~

### Scene

~~~
~~~

### Output

~~~
~~~

**Comment by c-lipka** [comment]
Took the liberty to strip some irrelevant portions from your issue report.

**Comment by c-lipka** [comment]
I'm not sure where you got the impression that "rendering is currently limited to video card RAM". As a matter of fact, POV-Ray 3.7.0's image buffer typically resides in main memory (regular RAM) or, if the size exceeds a certain threshold, in a temporary file on hard disk.

I can imagine that you might run into problems if you try to get a preview for an overly large image; in that case, the `-D` command-line switch (which suppresses preview output) should solve that problem.

If I'm misinterpreting your issue, please feel free to provide more detailed information about your set-up and how you're running POV-Ray (command-line options, maybe sample scene file), and I'll re-open the issue.

**Comment by jmichae3** [comment]
exactly ewhat I said - my video card is 2GB. the image buffer size is maximum 2GB. I have 55GB SDRAM free. I cannot do an image over the size of 16384x12288x16bitx3primarycolor. what does that tell you?

**Comment by jmichae3** [comment]
16384*12288*16*3/8bitsperbyte=1207959552bytes.

**Comment by jmichae3** [comment]
ummm, why is the camera backwards (require -x)?

**Comment by jmichae3** [comment]
in js, 
~~~~
x=(Math.sqrt(aspectRatio*55GBfree*Math.pow(2,30)*8bitsperbyte/bitspercolor/3colors))
y=(Math.sqrt(1/aspectRatio*55GBfree*Math.pow(2,30)*8bitsperbyte/bitspercolor/3colors))
~~~~

**Comment by c-lipka** [comment]
The GitHub issues are a place to track the status of bugs or new feature suggestions. For support or discussions, please _do_ visit our newsgroups.
