### ISSUE TITLE
Max_Image_Buffer_Memory=128?????

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#327]
### Summary

Max_Image_Buffer_Memory=128???? what unit is this? MiB?see 3.2.2.2 in manual, manual does not mention what unit this is supposed to be. RAM is measured in IEC units. so if this is MiB, the multiplier should be 2^20.  2^30 for GB of ram using today's RAM sizes. please advice in the manual. available RAM for heap for 64-bit is typically RAMSIZE-6GB-videocardramsize.

POV-RAy Reference\command-line and ini-file options\general output options\Max image buffer memory
--

Max_Image_Buffer_Memory=
--

### Environment

  - Source code Git tag: v3.7.0.0
  - POV-Ray version: v3.7.0+msvc10.win64
  - Operating system: Windows 7
  - Hardware platform: x86-64
  - Compiler: 
  - Regression from: 

### Windows Build Settings

  - Configuration: 
  - Platform: 
 
### Unix Build Command Sequence

~~~
cd unix ; prebuild.sh ; cd ..
./configure COMPILED_BY="John Doe <john.doe@fnord.com>"
make check
sudo make install
~~~

### Unix Pre-Build Output

~~~
~~~

### Unix Configure Output

~~~
~~~

### Compiler/Linker Output

~~~
~~~

### Steps to Reproduce

 1. 
 2. 
 3. 

### Render Settings

~~~
~~~

### Scene

~~~
~~~

### Output

~~~
~~~

**Comment by c-lipka** [comment]
For support, please visit our newsgroups at <http://news.povray.org> (or <news://news.povray.org> if you prefer acess via a newsreader).

Section 3.2.2.2 of the docs clearly identify the dimension of the parameter as "number of megabytes" (and yes, since this is RAM, we follow the convention that this is MiB, not MB).

**Comment by jmichae3** [comment]
not in 3.7.0 - multiplier is not documented.

**Comment by c-lipka** [comment]
http://www.povray.org/documentation/3.7.0/r3_2.html#r3_2_2_2

Quote: "This INI parameter sets the number of **megabytes** of RAM" (emphasis added)
