### ISSUE TITLE
Final_Frame is not used for calculating max number of digits in a number for frame number

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#328]
### Summary

Final_Frame is not used for calculating max number of digits in a number for frame number in an output file name like file001.png. problem is, it's stuck at 3 digits. I need more than that, I need to make a video.

### Environment

  - Source code Git tag: v3.7.0.0
  - POV-Ray version: v3.7.0+msvc10.win64 -->
  - Operating system: Windows 7
  - Hardware platform: x86-64
  - Compiler: 
  - Regression from: 

### Windows Build Settings

  - Configuration: 
  - Platform: 
 
### Unix Build Command Sequence

~~~
cd unix ; prebuild.sh ; cd ..
./configure COMPILED_BY="John Doe <john.doe@fnord.com>"
make check
sudo make install
~~~

### Unix Pre-Build Output

~~~
~~~

### Unix Configure Output

~~~
~~~

### Compiler/Linker Output

~~~
~~~

### Steps to Reproduce

 1. Initial_Frame=1, Final_Frame=7000
 2. 
 3. 

### Expected Behavior

you can simply convert the number to a string and find the string length to find out number of digits in a number. and yes, they should be zero-filled. not all programs know how to do this (ffmpeg for example).

### Actual Behavior

3 zero-filled digits in output filename and who knows what happens when it goes over this. does it wrap back to 000 or 001?

### Render Settings

Initial_Frame=1
Final_Frame=7000

~~~
~~~

### Scene

~~~
~~~

### Output

~~~
~~~

### Suggested Solution

you can simply convert the number to a string and find the string length to find out number of digits in a number. and yes, they should be zero-filled. not all programs know how to do this (ffmpeg for example).

**Comment by jmichae3** [comment]
I just got the inkling that you need to change the %1000 to only be active under
~~~~
#if defined(__DJGPP__)||(defined(__WATCOMC__)||defined(__MARSC))&&defined(__DOS__)
...filenumber%1000
#else
/*do not %1000 the output file number*/
#endif
~~~~

**Comment by dickbalaska** [comment]
I have run 2 digits to 4 digits with the width of the frame number correct.
Here is my ttfo.ini file that does 4 digits frame number filenames for me.
`; ttfo.ini -GA +GD +sf1 +ef1245
Width=720
Height=480
Final_Frame=1245
Input_File_Name=ttfo.pov
Output_File_Name=ttfo
Output_File_Type=n
Antialias_Depth=3
Antialias=On
Antialias_Threshold=0.3
Bounding=On
Bounding_Threshold=3
Continue_Trace=Off
Cyclic_Animation=On
Debug_File=debug.out
Final_Clock=1
Initial_Clock=0
Initial_Frame=1
Output_Alpha=Off
Pause_When_Done=Off
Quality = 9
Verbose=Off
Render_Block_Size = 16
Create_Continue_Trace_Log=off
`

**Comment by c-lipka** [comment]
There is no modulo-1000 for the frame number in the source code, and I can't reproduce your problem.

You've submitted 10 issue reports in just four days, and as far as I've read them, they all strongly smell like user errors to me.

Please do consult the manuals thoroughly, and **ask for support on the newsgroups**, to make sure you're seeing genuine bugs, before submitting any more issue reports.

As a courtesy, I'm repeating the newsgroup address here:

<http://news.povray.org>
<news://news.povray.org>

Also, please do read the issue report template and do follow our requests there to delete stuff not applicable to your type of issue report. As a rule of thumb, _if you don't fill in a section, please do delete it_!
