### ISSUE TITLE
FEATURE REQUEST: Frame_Number needed, concatenation of frame number to image file

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#329]
### Summary

- please add Frame_Number as an integer for calculations in things like rotations etc.. I did not find it in the manual under animation.
- please also add related string concatenation of zero-padded frame number to strings like image filepaths for input individual video frames. example: 
image_map {
jpeg "video_file1.jpg."+Frame_Number_Zero_Padded
}
wherre it comes out as "video_file1.jpg.5751" or "video_file1.jpg.0001" for Final_Frame=7000

### Environment

  - Source code Git tag: 
  - POV-Ray version: 
  - Operating system: 
  - Hardware platform: 
  - Compiler: 
  - Regression from: 

### Windows Build Settings

  - Configuration: 
  - Platform: 
 
### Unix Build Command Sequence

~~~
cd unix ; prebuild.sh ; cd ..
./configure COMPILED_BY="John Doe <john.doe@fnord.com>"
make check
sudo make install
~~~

### Unix Pre-Build Output

~~~
~~~

### Unix Configure Output

~~~
~~~

### Compiler/Linker Output

~~~
~~~

### Steps to Reproduce

 1. 
 2. 
 3. 

### Render Settings

~~~
~~~

### Scene

~~~
~~~

### Output

~~~
~~~

**Comment by dickbalaska** [comment]
frame_number
http://www.povray.org/documentation/3.7.0/r3_3.html#r3_3_1_5_6

**Comment by c-lipka** [comment]
Another support request in the guise of an issue.

Please acknowledge that we do not use GitHub issues as a support channel, except for reporting bugs or suggesting new features.
