### ISSUE TITLE
Please bring back disk buffering for large images (we have 10TB disks now and RAID)

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#331]
### Summary

Please bring back disk buffering for large images (we have 10TB disks now and RAID).
it was taken away in 3.6. it's a sore loss, as I cannot do images for large printed works at 300dpi like walls etc.

### Environment

irrelevant

### Windows Build Settings

  - Configuration: 
  - Platform: 
 
### Unix Build Command Sequence

~~~
cd unix ; prebuild.sh ; cd ..
./configure COMPILED_BY="John Doe <john.doe@fnord.com>"
make check
sudo make install
~~~

### Unix Pre-Build Output

~~~
~~~

### Unix Configure Output

~~~
~~~

### Compiler/Linker Output

~~~
~~~

### Steps to Reproduce

 1. 
 2. 
 3. 

### Expected Behavior

Buffer_Output and Buffer_Size (I would replace Buffer_Size) should be brought back, but with some more smarts, like replacing Buffer_Size with
Buffer_Width
Buffer_Height
Buffer_Bits_Per_Color
and let the program calculate this stuff automatically. the math for calculating size should also be put in the manual.
Buffer_Size=ceil(Buffer_Width*Buffer_Height*Buffer_Bits_Per_Color*3.0/8.0)

and a buffer size calculator is needed in the GUI.

### Actual Behavior

3.2.4.3 Output File Buffer
The output-file buffer options Buffer_Output and Buffer_Size are removed per POV-Ray 3.6

Note: The options are still accepted, but ignored, in order to be backward compatible with old INI files.

### Render Settings

~~~
~~~

### Scene

~~~
~~~

### Output

~~~
~~~

**Comment by c-lipka** [comment]
Duplicate to earlier issue (I won't even bother to look which one), and unsubstantiated besides. Turn to our newsgroups for support on how to render large files without running into limitations. Thank you for your cooperation.
