### ISSUE TITLE
include files are all copyrighted - no permission statement - ugh no glass I can use

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#332]
### Summary

include files and manual are all copyrighted - no permission statement - ugh no glass or wood I can use.
if you want people to use your stuff, you have to leave them pretty much uncopyrighted. otherwise it's just a doorstop and Engineers don't want to mess with it because they can't get permission. and by the way, the GPL license's copyrights are not legally defensible because they did not go through copyright.gov. there is a default non-legally-defensible copyright which they require you to do.
please take the copyrights out so we can all have fun with POV-RAY. thank you.

### Environment

  - Source code Git tag: 
  - POV-Ray version: 
  - Operating system: 
  - Hardware platform: 
  - Compiler: 
  - Regression from: 

### Windows Build Settings

  - Configuration: 
  - Platform: 
 
### Unix Build Command Sequence

~~~
cd unix ; prebuild.sh ; cd ..
./configure COMPILED_BY="John Doe <john.doe@fnord.com>"
make check
sudo make install
~~~

### Unix Pre-Build Output

~~~
~~~

### Unix Configure Output

~~~
~~~

### Compiler/Linker Output

~~~
~~~

### Steps to Reproduce

 1. 
 2. 
 3. 

### Render Settings

~~~
~~~

### Scene

~~~
~~~

### Output

~~~
~~~

**Comment by c-lipka** [comment]
`glass.inc` clearly states its license (as do all the other include files, as well as the docs):
> This work is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License.
(Note that some files use a different CC license.)

Copyright does not need to be registered.
