### ISSUE TITLE
AX_FIX_INCORRECT_PATH is broken

### ISSUE THREAD

**Issue by nolta** [POV-Ray/povray#342]
`configure` incorrectly strips all periods from `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH`, because `AX_FIX_INCORRECT_PATH` is buggy. Here's the relevant part of `config.log`:

```
ax_fix_incorrect_path_regexp = [=:]*\.:*
ax_fix_incorrect_path_old = /path/with.dots/include
ax_fix_incorrect_path_new = /path/withdots/include
configure:4428: checking whether $C_INCLUDE_PATH contains the "." path
configure:4431: result: yes
configure:4433: WARNING: $C_INCLUDE_PATH is incorrectly set with the "." path
```

Note that `/path/with.dots/include` gets turned into `/path/withdots/include`.

`ax_fix_incorrect_path_regexp` needs to be fixed.

### Environment

  - POV-Ray version: 3.7.0.4
  - Operating system: Linux

**Comment by c-lipka** [comment]
It seems to me that it would also wreck any path actually listing the "." directory somewhere in the middle; e.g., `foo:.:bar` would not be converted to `foo:bar`, but rather to `foobar`.
