### ISSUE TITLE
Bad naming in Insert Menu / 10 - Ready made scenes

### ISSUE THREAD

**Issue by gryken2014** [POV-Ray/povray#36]
In "10 - Ready made scenes" directory, for example :

10 - Basic Scene 01 - Checkered plane.txt
10 - Basic scene 01 - Checkered plane.jpg

With text files, there is "Scene".
With jpg files, there is "scene".

It is harmless under Windows (non case sensitive file-system)
But, it can be under unix-like (case sensitive file-system)

**Comment by c-lipka** [comment]
These files reside in the "distribution/platform-specific/windows" directory, so I don't see much of a problem there. Leaving the issue open though, so that it won't be entirely forgotten.
