### ISSUE TITLE
Pov-ray ignores [Permitted Output Paths]

### ISSUE THREAD

**Issue by sbandx** [POV-Ray/povray#366]
### Summary

I can't seem to get Pov-Ray 3.7 to output to a custom output folder when rendering after specifying c:\render as my output file directory
### Environment

Windows 10 - standard installation

  - Source code Git tag: 
  - POV-Ray version: 
  - Operating system:  Windows 10
  - Hardware platform: x86-64, ARM -->

### Steps to Reproduce

 1. set 
[Permitted Output Paths]
1=%PROFILEDIR%\Insert Menu
2=c:\render

 2. render image from pov file

### Expected Behavior
It should have produced a png file in c:\render
### Actual Behavior

 3. This only renders to the folder where the .pov file is

### Render Settings

pvengine.ini:
[Permitted Output Paths]
1=%PROFILEDIR%\Insert Menu
2=c:\render
~~~
~~~

### Output
Preset INI file is 'C:\Users\Prnx\Documents\POV-Ray\ini\quickres.ini', section is '[512x384, No AA]'.
Preset source file is 'C:\Users\Prnx\Documents\POV-Ray\MyScenes\ring-sphere.pov'.
Rendering with 4 threads.
Parser Options
  Input file: C:\Users\Prnx\Documents\POV-Ray\MyScenes\ring-sphere.pov
  Remove bounds........On
  Split unions.........Off
  Library paths:
    C:\Users\Prnx\Documents\POV-Ray\include
    C:\windows\Fonts
  Clock value:    0.000  (Animation off)
Image Output Options
  Image resolution.....512 by 384 (rows 1 to 384, columns 1 to 512).
  Output file..........C:\Users\Prnx\Documents\POV-Ray\MyScenes\ring-sphere.png, 32 bpp with alpha PNG
  Dithering............Off
  Graphic display......On  (gamma: sRGB)
  Mosaic preview.......Off
  Continued trace......Off
Information Output Options
  All Streams to console..........On
  Debug Stream to console.........On
  Fatal Stream to console.........On
  Render Stream to console........On
  Statistics Stream to console....On
  Warning Stream to console.......On

Parser Statistics

Finite Objects:           30
Infinite Objects:          0
Light Sources:             1
Total:                    31

Parser Time
  Parse Time:       0 hours  0 minutes  0 seconds (0.156 seconds)
              using 1 thread(s) with 0.140 CPU-seconds total
  Bounding Time:    0 hours  0 minutes  0 seconds (0.000 seconds)
              using 1 thread(s) with 0.000 CPU-seconds total

Render Options
  Quality:  9
  Bounding boxes.......On   Bounding threshold: 3
  Antialiasing.........Off

Render Statistics
Image Resolution 512 x 384

Pixels:           196608   Samples:               0   Smpls/Pxl: 0.00
Rays:             199525   Saved:                 0   Max Level: 3/5

Ray->Shape Intersection          Tests       Succeeded  Percentage

Sphere                             320              49     15.31
Torus                            28565           13903     48.67
Torus Bound                      28565           16142     56.51
~

**Comment by c-lipka** [comment]
Note that "**Permitted** Output Paths" does not mean **actual** output path. To actually create an output image in `c:\render` you will have to specify `Output_File_Name=c:\render\` in the scene's INI file (or, if you always want to render to that directory, in the master `povray.ini`).

The "permitted output paths" mechanism is a security safeguard, in case you render scenes you get from other people, so that they can't mess with your system in unexpected ways.

**Comment by sbandx** [comment]
I did that but I think I stuck it in pvengine.ini and not povray.ini I will try it againOn Oct 13, 2018 15:29, Christoph Lipka <notifications@github.com> wrote:Note that "Permitted Output Paths" does not mean actual output path. To actually create an output image in c:\render you will have to specify Output_File_Name=c:\render\ in the scene's INI file (or, if you always want to render to that directory, in the master povray.ini).
The "permitted output paths" mechanism is a security safeguard, in case you render scenes you get from other people, so that they can't mess with your system in unexpected ways.

**Comment by sbandx** [comment]
Wrote to the wrong ini file
