### ISSUE TITLE
VS 2017 custom Windows build doesn't start

### ISSUE THREAD

**Issue by schmedward** [POV-Ray/povray#367]
### Summary

 It doesn't even get to WinMain before exiting with code 255.

### Environment

  - Source code Git tag: 
  - POV-Ray version: 
  - Operating system: 
  - Hardware platform: 
  - Compiler: 
  

### Windows Build Settings

  - Configuration: 
  - Platform:

**Comment by c-lipka** [comment]
You may want to provide a little more detail.

**Comment by c-lipka** [comment]
Closing due to lack of detail.
