### ISSUE TITLE
Missing txt file in /E6 - Patterns 2/03 - pavement_sides_3

### ISSUE THREAD

**Issue by gryken2014** [POV-Ray/povray#37]
There is a file named "pavement_s3_t6_p12.txt".
But the file "pavement_s3_t6_p12..jpeg" doesn't exist.

**Comment by c-lipka** [comment]
Hum... I see the exact opposite: A .jpg file, but no matching .txt file.

**Comment by gryken2014** [comment]
I have switched the filenames...

The TXT file is missing.
The JPEG file is in the directory.
