### ISSUE TITLE
Error C2039: 'strdup': is not a member of 'std'

### ISSUE THREAD

**Issue by trevorsandy** [POV-Ray/povray#370]
The povparser module build fails on MSVC (I'm using VS2017) with the following return: 

`..\..\source\parser\fncode.cpp(197): error C2039: 'strdup': is not a member of 'std'`

The failure can be traced to this line of code:
https://github.com/POV-Ray/povray/blob/0f3efc8edce08d60b9eee1df5f9b904ace7e6dd7/windows/povconfig/syspovconfig.h#L172

Builds succeed when `std::strdup(str)` is replaced with` _strdup(str)`.

Cheers,

**Comment by c-lipka** [comment]
Thanks for spotting this. Good to know someone is keeping an eye on the Windows console version of POV-Ray.

Fixed in the master branch, and will be included in the next tagged version.
