### ISSUE TITLE
MacOS build fail Povray

### ISSUE THREAD

**Issue by Aiyush-G** [POV-Ray/povray#402]
Hi everyone, 

Here is my error:
`:-1: error: No rule to make target `../leocad/povray', needed by `build/debug/LeoCAD.app/Contents/MacOS/povray'.  Stop.`

This causes the build to fail, could you help?

Thanks

**Comment by trevorsandy** [comment]
Download the povray binary from https://github.com/leozide/povray/releases and place it at the same location as the Qt project (.pro) file.

Cheers,

**Comment by Aiyush-G** [comment]
Oh right, thanks! It is working now. On a separate note: are there any guides for customising LeoCad ie. Changing application name/icon. My main aim is to adapt the program for a school project to create modular designs- not legos but just stl files? Any ideas how to do this? 

Thanks @trevorsandy  and any help would be appreciated

**Comment by trevorsandy** [comment]
Hi. 

Certainly you can change the LeoCAD name and icon if you are building from source but first, close this ticket if your povray issue is resolved then open a ticket in the LeoCAD GitHub repository with your inquiry.

Cheers,

**Comment by Aiyush-G** [comment]
Yup, thanks!
