### ISSUE TITLE
cannot build latest trunk

### ISSUE THREAD

**Issue by KammutierSpule** [POV-Ray/povray#43]
The build starts and it stops in some seconds:

In file included from ./core/coretypes.h:45:0,
                 from ./backend/frame.h:63,
                 from ./backend/vm/fnpovfpu.h:47,
                 from ./parser/fncode.h:44,
                 from parser/fncode.cpp:46:
./core/math/vector.h: In function ‘double (* pov::Create_Vector_4D())[4]’:
./core/math/vector.h:75:83: error: ‘POV_MALLOC’ was not declared in this scope
     New = reinterpret_cast<VECTOR_4D *>(POV_MALLOC(sizeof (VECTOR_4D), "4d vector"));
                                                                                   ^
./core/math/vector.h: In function ‘void pov::Destroy_Vector_4D(double (*)[4])’:
./core/math/vector.h:96:19: error: ‘POV_FREE’ was not declared in this scope
         POV_FREE(x);
                   ^
make[2]: *** [parser/fncode.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by c-lipka** [comment]
Should be fixed now.
