### ISSUE TITLE
Cannot Register on povray.org news/forums

### ISSUE THREAD

**Issue by kennebel** [POV-Ray/povray#441]
I tried to follow the directions to start a new conversation on the news/forums location, but I cannot complete step #2, as the email with verification code is not being sent to me. I did check spam folders already. :)

**Comment by chris20** [comment]
I see nothing in the user DB that appears to relate to your registration, though I cannot be sure without knowing your email address. Please contact us via the address given at https://www.povray.org/webmaster.html and provide the email address you were using (preferably also with an IP address) and with the exact steps you took.

**Comment by kennebel** [comment]
Email sent as requested. Thank you for the help.

**Comment by chris20** [comment]
For future reference (as this issue still exists): Google has somehow come to the conclusion that the POV-Ray project are spammers and have blocked all email from both the povray.org server and the domain itself. They provide no explanation as to why other than the generic "you are sending unsolicited email". We are not on any other blocklists.

Given there's no clear cause nor clear resolution there's unlikely to be a fix for this anytime soon.

For the time being I've added a warning to the registration form that tells users with gmail (or gmail-hosted) addresses that they probably won't get the verification email.
