### ISSUE TITLE
[BUG][WINDOWS] 

### ISSUE THREAD

**Issue by Saxomania** [POV-Ray/povray#443]
Pov-ray for Windows
3.7.0.msvc10.win64

Windows 10 1809 LTSC 64bit
x64
Intel Core i7 7820HQ @ 2.90 Ghz

Error message as default user (no admin rights)

Cannot open INI file 'C:\Program Files\Pov-Ray\v3.7\Ini\povray.ini More Resolutions ...'
Failes to start render: failed to parse INI file

If i run it under logged on user with admin rights it works without problem (but dont run pov-ray as admin)

checked C:\Program Files\Pov-Ray\v3.7\Ini\povray.ini, its accessable for every user
added write/change rights for default user but no change in error message

how to dig deeper? Any error log available?

**Comment by HackerDaGreat57** [comment]
`C:\Program Files` is a special folder. Windows will always treat it with some level of security no matter who has access to it.

**Comment by Saxomania** [comment]
solved it that way:

During the installation, the path to the user data path for the program is requested in addition to the program path.
program, this must be done independently from each other

apparently the installation under Admin A is done OK (if you consider the previous section) but when user U logs in, then the user data path seems to be
not set, can be done manually here:

Computer\HKEY_CURRENT_USER\Software\POV-Ray\v3.7\Windows

DocPath (RegSZ) and then set the right path \username\Documents\POV-Ray\v3.7

then you have to copy the user data from A to U.

During the installation it is still to be noted that a desktop symbol is put on however only for the one who installs it and so it does not show up in the start menu for all others than A so copy it from the desktop to:

c:\ProgramData\Microsoft\Windows\Start Menu\Programs

Translated with www.DeepL.com/Translator (free version)
