### ISSUE TITLE
Povray fail to build

### ISSUE THREAD

**Issue by abecke12** [POV-Ray/povray#46]
Povray is failing to build "Error: povray 3.7.0.0 did not build" when using the "brew install -v povray" command.
Errors were all within the 'makeinstall' section.

I have searched the forums but haven't seen anything I can implement myself to fix this issue.

(Can't attach log files since I don't have write permission?)

**Comment by c-lipka** [comment]
Please be aware that you are using an unsupported build process.

Also, from what I gather on the 'net, you seem to be trying to build POV-Ray on Mac OS X. There is currently no official Mac OS X support for POV-Ray. Note however that an unofficial Mac port can be found on http://megapov.inetart.net/povrayunofficial_mac/index.html#Mac.

**Comment by abecke12** [comment]
What would a supported build process be? I've no idea how to use Macports, but I shall try the website you have given me, thank you.

**Comment by c-lipka** [comment]
Just for clarification: The unofficial POV-Ray Mac port referred to above does not use the "MacPorts" project.

**Comment by dunn** [comment]
Understanding that the Homebrew build is unsupported, here are logs for the failure we're seeing, if you're curious: https://gist.github.com/anonymous/c40518ffa0379f708bb7 (https://github.com/Homebrew/homebrew/issues/45317)

**Comment by c-lipka** [comment]
To my knowledge, this seems to have been fixed in homebrew. Can someone confirm?

**Comment by dunn** [comment]
The Homebrew formula is working for me on El Capitan.

**Comment by abecke12** [comment]
Yes it is now working for me in Yosemite.
