### ISSUE TITLE
Degraded Performance

### ISSUE THREAD

**Issue by c-lipka** [POV-Ray/povray#48]
Performance has declined since the official 3.7.0 release.

On Ubuntu 14.04.04, the inbuilt benchmark is reported to be running about 19% slower for 3.7.1-alpha.8344733; on Windows 7, a difference of about 17% has been measured.

The reason for this difference needs to be examined.

**Comment by toddcarnes** [comment]
I ran some unofficial tests of my own as follows:

1. I downloaded and installed the official POV-Ray for Windows 3.7.0.0.
2. I ran the official benchmark test 3 times then averaged the results.
3. I downloaded & compiled from git POV-Ray for Windows 3.7.1-alpha.8344735.unofficial.msvc14.win64.
4. I ran the official benchmark three times and averaged the results.

My results basically agreed with yours. Official version 3.7.0.0 runs 1.23 times faster than unofficial version 3.7.1.alpha. However, I also noticed another significant difference. Official version 3.7.0.0 also uses 1.83 times as much memory as version 3.7.1.alpha.

So, it would appear that you have traded a slower rendering speed for better use of available memory.

A more detailed version of my testing is in the attached file.
[povrayTR.txt](https://github.com/POV-Ray/povray/files/35118/povrayTR.txt)

**Comment by wfpokorny** [comment]
I had occasion to compile both stable and master today so checked again the performance of the benchmark as I know master has changed quite a lot since this was opened. 

Ubuntu 14.04
stable -> 3.7.1-alpha.8581629
CPU    1104.82 seconds -> 1310.64 seconds 18.63%
Memory 34824KB -> 34296KB -1.52%

As before reported statistic more or less the same - media samples up 1.52% .  I'll put it on my list to later attempt a couple profiled runs.

**Comment by wfpokorny** [comment]
Attached is a quick view of gprof results comparing 3.7.0-stable to 3.7.1-alpha.8581629.

Both compiled with all optimization off and run with one thread with the command: 
povray --benchmark +wt1

The full output is about 30MB - most of it related to things not consuming much time.

[Quick_gprof_view.txt](https://github.com/POV-Ray/povray/files/238504/Quick_gprof_view.txt)

**Comment by wfpokorny** [comment]
In looking to clean up some old FlySpray tasks had occasion to run the attached SplineThreadSafety.pov file in both 3.7.0-Stable and our 3.7.1 branch at commit : 598f29aff140675b99305fdcb051482bb5ed7bbd 

I was somewhat surprised to find our 3.7.1 branch is 28.8% slower which is a good deal more slow down than we see with the benchmark. 2 Core I3. Ubuntu 16.04. 

[SplineThreadSafety.pov.txt](https://github.com/POV-Ray/povray/files/521873/SplineThreadSafety.pov.txt)

**Comment by wfpokorny** [comment]
Tracked the bulk of the 3.70 to 3.71+ benchmark performance degrade to two commits in 725efe1 (+11%) and 1b5aab6 (+3.5%). 

Note! The impact due the abstraction of the virtual machine interface in 1b5aab6 is much more severe in isosurface only scenes at about +20% for relatively simple functional combinations. Most of the vm degrade looks to be due the use of dynamic_cast in performance critical code. I'm looking at how we avoid most of the penalty with a "Visitor Design Pattern", but I'm still near the bottom of the C++ learning mountain, so who knows when or if I'll get to a workable fix.        

Aside: I ended up using some of the perf tools part of the linux-tools collection as the gprof tool with which I was familiar doesn't show the dynamic_cast time (suppose it might with the right -p compiled libraries).  

I suspect much of the reason for the benchmark degrade in 725efe1 was the significant move to c++ new/delete in that commit over the previous malloc/free, but I have done no actual profiling in this case.   

Reference:
-------------------------

povray_1cceb44 -- 1243.34
povray_c891131 -- 1243.62
povray_eeeb2c5 -- 1239.16
povray_d1d01eb -- 1252.21
povray_9bacee3 -- 1240.73
povray_cbe3c65 -- 1235.53
                                                       
* 1b5aab6 More refactoring and moving around of code, primarily to further disentangle the different components of POV-Ray:  +3.5%

povray_aaff0bb -- 1190.06
povray_dc0fc6d -- 1205.08
povray_0c7f977 -- 1198.50 1194.78
povray_58d51f4 -- 1190.88
povray_3f56c5f -- 1199.79

* 725efe1 Merge branch 'refactor'                     +11%
* 1fac52a Merge branch 'feature/unit_tests' (Adding shipped windows boost)
* 845851e Source code documentation pertaining to entities spanning more than one file (namespaces, directories) now resides in `source-doc/*.dox`.

povray_e16458c -- 1081.26
povray_ca0d798 -- 1087.02
povray_9b10411 -- 1073.27
povray_2c4e9f2 -- 1059.80
povray_f69d768 -- 1068.06

**Comment by c-lipka** [comment]
Thanks for taking the time to get to the bottom of this.

I wouldn't want to mess with the VM interface during the beta phase, and rather bite the bullet of sub-optimal performance in 3.7.1. Even in the development leading up to 3.7.2 I would prefer to first replace the current VM implementation with one based on LLVM, and then see how we can improve things -- maybe even ditch the polymorphism again.

But I'll have a look whether there are some instances of `dynamic_cast<>` that can easily be replaced with `static_cast<>`.

**Comment by c-lipka** [comment]
Maybe have a look at commit 8a8b503; according to my measurements, it roughly counteracts the performance loss you measured for 1b5aab6.

**Comment by wfpokorny** [comment]
THANKS! In my initial testing the performance is indeed restored - maybe even a touch faster - measuring user cpu over repeated renders. 

I'll later take a  look at your actual code changes and play more with these newer linux profiling tools I have just gotten running on additional test cases. The linux perf tool in particular has many cool features - if not very good documentation.

**Comment by wfpokorny** [comment]
More work on performance.

Pull request #258 recovers about 25% of the benchmark slow down in commit 725efe1 primarily by avoiding a dynamic_cast on every call to patterns calling SearchForTurb. As with the vm issue recently, this change might have anything from a very dramatic effect to almost no effect at all depending on how heavily specific patterns - like agate - are used.

With the pull request the performance degrade from 3.7.0 to 3.7.1 is down to about 7.2% - if comparisons are run where the number of threads are equal to the number of cores or less (no hyperthreading) on an otherwise relatively quiet system. It turns out where the numbers of threads is greater than the number of cores the 3.7.0 to 3.7.1 performance degrade is worse at about 11%. While using hyperthreads is still a win in better wall clock time the benefit is reduced. My suspicion is more threads than cores causes poorer caching and that our 3.7.1 is for some reason less cache friendly.

Aside: Adding -std=c++11 to the gnu compiler flags on my Ubuntu system is buying me about 1% better performance and a slightly smaller executable.

**Comment by c-lipka** [comment]
Have a look at the current release/v3.7.1 branch. I see an increase in benchmark performance of about 21% over beta.4 now, which should just about offset the performance loss we saw.

Thanks to the hardware-specific noise optimizations and the migration from VS 2010 to VS 2015, I now see a net increase in benchmark performance of about 28% over official 3.7.0.

**Comment by wfpokorny** [comment]
Thanks for running down those other dynamic_cast issues! Liked too your fix over my earlier proposed one.  

Performance is closer to restored, but on my i3 (2 core 4 thread) Ubuntu 16.04 system I'm still seeing about 1.8% slower for two threads and 5.7% slower for 4 threads. 

So, yesterday, I ran down another smallish issue in the older 1fac52a to 3f56c5f transition only to come back to the current code to find you'd already cleaned up some of the obvious stuff over time! :-) I think with that effort and result I'm done looking at differences in the older commits showing the large changes in performance.  
  
Suppose I'm sitting with the feeling what is left is indeed C++ being a little slower than older C code. For example the std lib vector class being slower - but not dramatically so. With the vector class I have a strong-ish suspicion our memory use is less cache friendly. Maybe at some point I'll set up a render with a large mesh and do some profiling to better test this theory. 

Lastly, I think we can close this issue as I think the 3.7.0 to 3.7.1 degrade in performance is as directly addressed as it is going to be. We can open more targeted performance issues on the current code as needed.
