### ISSUE TITLE
Latest version from Git won't build with MS Visual Studio 2015

### ISSUE THREAD

**Issue by toddcarnes** [POV-Ray/povray#49]
After reading Bug #48, I tried to build the 64 bit version from git (commit #4983507) on Windows 10 so I could compare it with the official 3.7.0.0 release. Unfortunately, it refuses to build with Visual Studio 2015 Community Edition.

There were MANY warnings, but the errors that stopped the build were as follows:

Severity	Code	Description	Project	File	Line

Error	C2440	'initializing': cannot convert from 'overloaded-function' to 'const pov::Sys1'	povbackend	C:\src\povray\source\backend\vm\fnpovfpu.cpp	491
Error	C2668	'acosh': ambiguous call to overloaded function	povparser	C:\src\povray\source\parser\parser_expressions.cpp	754
Error	C2668	'asinh': ambiguous call to overloaded function	povparser	C:\src\povray\source\parser\parser_expressions.cpp	757
Error	C2668	'atanh': ambiguous call to overloaded function	povparser	C:\src\povray\source\parser\parser_expressions.cpp	760
Error	C2668	'asinh': ambiguous call to overloaded function	povparser	C:\src\povray\source\parser\parser_functions.cpp	1203
Error	C2668	'acosh': ambiguous call to overloaded function	povparser	C:\src\povray\source\parser\parser_functions.cpp	1206
Error	C2668	'atanh': ambiguous call to overloaded function	povparser	C:\src\povray\source\parser\parser_functions.cpp	1209
Error	LNK1181	cannot open input file 'C:\src\povray\windows\vs10\bin64\lib\povbackend64.lib'	GUI	C:\src\povray\windows\vs10\LINK	1

The full list of errors & warnings is attached.
[error.txt](https://github.com/POV-Ray/povray/files/34970/error.txt)

**Comment by c-lipka** [comment]
The only Windows-based compiler officially supported for building POV-Ray v3.7.0.0 is Microsoft Visual Studio 2010; as a matter of fact, de-facto support for VS 2015 has only been added within the last few days.

**Comment by c-lipka** [comment]
Sorry, I misread the OP.
