### ISSUE TITLE
Make error in Ubuntu 14.04

### ISSUE THREAD

**Issue by Markbanfd** [POV-Ray/povray#50]
I'm using Ubuntu 14.04 and I'm trying to install Povray, according to the instructions in https://github.com/POV-Ray/povray/tree/3.7-stable/unix

I checked that all dependencies are up to date (libboost-dev, zlib1g-dev libpng12-dev, libjpeg8-dev, libtiff5-dev, libopenexr-dev), and then I do the following as suggested in the git website:

cd unix/
./prebuild.sh
cd ../
./configure COMPILED_BY="your name <email@address>"
make

The ./prebuild.sh and ./configure are performed successfully but the make step gives the following error:

make  all-recursive
make[1]: Entering directory `/home/mark/Desktop/povray/povray'
Making all in source
make[2]: Entering directory `/home/mark/Desktop/povray/povray/source'
depbase=`echo core/scene/object.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    g++ -DHAVE_CONFIG_H -I. -I..  -I../unix/povconfig -I.. -I../unix -I../vfe -I../vfe/unix -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -pthread -I/usr/include/OpenEXR    -pthread -I/usr/include  -I/usr/include  -pipe -Wno-multichar -Wno-write-strings -fno-enforce-eh-specs -Wno-non-template-friend -s -O3 -ffast-math -march=native -pthread -MT core/scene/object.o -MD -MP -MF $depbase.Tpo -c -o core/scene/object.o core/scene/object.cpp &&\
    mv -f $depbase.Tpo $depbase.Po
In file included from ./core/configcore.h:41:0,
                 from core/scene/object.cpp:39:
./base/mathutil.h: In function ‘T pov_base::wrap(T, T)’:
./base/configbase.h:646:39: error: ‘NO_OP’ was not declared in this scope
     #define POV_MATHUTIL_ASSERT(expr) NO_OP
                                       ^
./base/mathutil.h:111:5: note: in expansion of macro ‘POV_MATHUTIL_ASSERT’
     POV_MATHUTIL_ASSERT((tempVal >= 0.0) && (tempVal < upperLimit));
     ^
make[2]: *** [core/scene/object.o] Error 1
make[2]: Leaving directory `/home/mark/Desktop/povray/povray/source'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/mark/Desktop/povray/povray'
make: *** [all] Error 2

**Comment by c-lipka** [comment]
Fix verified on Ubuntu 14.04 LTS.
