### ISSUE TITLE
Download branch and configure option

### ISSUE THREAD

**Issue by jerome-msra** [POV-Ray/povray#51]
I've tried to compile & build povray on Mac OS X El Capitan and found the following issues.

1. For downloading. I downloaded the source from the official website, and it's stable branch. However when I tried to compile, the shared_ptr issue still exists. After a bit of working I found that the issue was fixed in the master branch. So It would be better to address it when the user downloads the package.

2. For configure. When I executed ./configure, it always said: "couldn't link to boost thread library". I found lboost-thread-mt in my computer and added that option and the configure process went further. However, it then stuck at linking to boost system library. That was found when I checked out the config.log file. If the options have been added into the configure file or these comments are included in the documentation, the user will be happier.

**Comment by c-lipka** [comment]
As of commit 4f3f49e, the stable branch should now build ok on OS X.
