### ISSUE TITLE
Not the right behaviour for Bezier splines 

### ISSUE THREAD

**Issue by Lanuhum** [POV-Ray/povray#60]
http://news.povray.org/povray.binaries.images/message/%3Cweb.5727406d27a8e5387a3e03fe0%40news.povray.org%3E/#%3Cweb.5727406d27a8e5387a3e03fe0%40news.povray.org%3E

File '/tmp/Empty.pov' line 17: Parse Error: Incorrect point in lathe.
Fatal error in parser: Cannot parse input.
Render failed

#version 3.7;

#include "functions.inc"
global_settings {
    assumed_gamma 1.000000
    max_trace_level 3
    charset utf8
}
sky_sphere {
    pigment {rgb<0.050, 0.050, 0.050>}
}

#declare Default_texture = texture{pigment {rgb 0.8}}

#declare data_Lathe_shape_ob =
lathe { bezier_spline 8,
    <0,1><0.25,0.75><-0.07594,0.5><0.1875,0.1875>
    <0.1875,0.1875><0.3929,-0.05616><0,-0.5><0,-1>
}
object {data_Lathe_shape_ob
    texture {Default_texture}
    matrix <1.000000, 0.000000, 0.000000,  0.000000, -0.000000, -1.000000,  0.000000, 1.000000, -0.000000,  0.000000, 0.000000, 0.000000>
}

light_source {
    <5.07,5.58,4.28>
    color rgb<1, 1, 1>
    fade_distance 25.0000000000
    fade_power 1
}
camera {
    perspective
    location  <0,0,0>
    look_at  <0,0,-1>
    right <-1.7777777777777777, 0, 0>
    up <0, 1, 0>
    angle  49.134343
    rotate  <-27.098163, 46.688390, -0.903519>
    translate <7.481132, 5.343666, 6.507640>
}

**Comment by wfpokorny** [comment]
Attaching a large set of spline related test cases used in part to evaluate a code update to permit negative control points in a bezier spline lathe. 
[lathePrismSplineIssuesTestCases.tar.gz](https://github.com/POV-Ray/povray/files/264502/lathePrismSplineIssuesTestCases.tar.gz)

**Comment by c-lipka** [comment]
I think this should be fixed with commit 2ec4a4e / pull request #62.
