### ISSUE TITLE
Can't find configure

### ISSUE THREAD

**Issue by andrewdalecramer** [POV-Ray/povray#61]
I'm trying to compile the latest version of povray on a linux computer (CentOS) which I don't have admin rights on.

I've downloaded the source but can't find the configure script. Running autoconf in unix/ says it can't find a bunch of files under unix/, running autoconf on unix/configure.ac says it can't find VERSION.

povray$ find | grep configure
./unix/configure.ac
./libraries/jpeg/configure
./libraries/jpeg/configure.ac
./libraries/zlib/configure
./libraries/zlib/contrib/minizip/configure.ac
./libraries/openexr/configure
./libraries/openexr/configure.ac
./libraries/png/configure
./libraries/tiff/configure
./libraries/tiff/configure.ac
./libraries/ilmbase/configure
./libraries/ilmbase/configure.ac

**Comment by eblanca** [comment]
Just run prebuild.sh, it will create the configure script.

**Comment by andrewdalecramer** [comment]
Thanks, would you like me to submit a patch to update the instructions in unix/install.txt?

**Comment by c-lipka** [comment]
No need to submit a patch; if you have a look at the master branch, you should find `prebuild.sh` already mentioned prominently in `unix/install.txt`.
