### ISSUE TITLE
Normal for the prism's bezier spline mode is reversed from other spline types & lathe uses.

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#65]
The issue is that the normal for the prism bezier spline is reversed from all other spline uses in both lathes and prisms. See the attached tarball for the README, test cases, some pre-rendered.

[PrismBezierNormalFlipped.tar.gz](https://github.com/POV-Ray/povray/files/271192/PrismBezierNormalFlipped.tar.gz)

**Comment by wfpokorny** [comment]
New version of test cases where both prism ends are visible to the camera given the discovery here: 

http://news.povray.org/57533e83%40news.povray.org

[PrismBezierNormalFlipped_V0.1.tar.gz](https://github.com/POV-Ray/povray/files/299339/PrismBezierNormalFlipped_V0.1.tar.gz)

**Comment by LeForgeron** [comment]
There is two issues, separate:
* the orientation of bezier_spline prism's side normal
* for all prism, the lower face has the same orientation as the upper face, so interior_texture is doomed to fail.

**Comment by wfpokorny** [comment]
Let us add a third normals issue to this github issue...

* The normals for sides of text objects is also flipped from what it should be. In searches found this has been mentioned on and off in the news groups. 

In the attached image we should not see the red interior texture at all, but we do on the text object sides. 

![textobjectsidenormalflipped](https://cloud.githubusercontent.com/assets/15925553/24864115/2f7dd0be-1dd1-11e7-8031-9e3e7a95d6a6.jpg)

**Comment by LeForgeron** [comment]
For the text object, It might be fixed with 

https://github.com/LeForgeron/povray/commit/2595932240ea8caa99b2a9c610c8af9d90ff0558

(yep, it is !)

**Comment by wfpokorny** [comment]
Thanks  Jérôme. Now that you mention it I do remember your version of POV-Ray getting this fix...  I did it in my pull request as an afterthought to the performance changes which where my primary interest.

**Comment by wfpokorny** [comment]
Closing. 

Ran all the tests again plus additional text cases to look at the normal changes there and all is fixed with e7aac79. 

For anyone picking up these tests again note a few stacked ring orthographic camera ones are noisy at the edges. Further there have been change from say v370 to v380 - the ambient default for example which affects the test case results herein.
