### ISSUE TITLE
bicubic_patch & clipped_by

### ISSUE THREAD

**Issue by LeForgeron** [POV-Ray/povray#69]
bicubic_patch does not perform clipped_by operation, but it works fine with intersection.

Here the variant with clipped_by
![lyu](https://cloud.githubusercontent.com/assets/6189221/15973860/d8e52038-2f45-11e6-8645-83f16df6d5a4.png)
and there the one with intersection:
![lyui](https://cloud.githubusercontent.com/assets/6189221/15973866/ddffdf0e-2f45-11e6-9c1d-eace38639e62.png)
Attached scenes to reproduce
[bicub.tar.gz](https://github.com/POV-Ray/povray/files/309506/bicub.tar.gz)

It would be great to have clipped_by working also with bicubic_patch

**Comment by c-lipka** [comment]
This should have been fixed by Commit 6e20d0b (2015-02-13, "Fixed bezier patch not honouring clipped_by statement.")

Are you sure you tested this with the latest development (master branch) version?

**Comment by LeForgeron** [comment]
You are correct, this is fixed in master branch.
